export type RoundStats = {
  playerid: string
  game: number
  team: string
  opponent: string
  roundnumber: string
  year: number
  result: string
  jumpernumber: number
  kicks: number
  marks: number
  handballs: number
  disposals: number
  goals: number
  behinds: number
  hitouts: number
  tackles: number
  rebound50s: number
  inside50s: number
  clearances: number
  clangers: number
  freekicksfor: number
  freekicksagainst: number
  brownlowvotes: number
  contestedpossessions: number
  uncontestedpossessions: number
  contestedmarks: number
  marksinside50: number
  onepercenters: number
  bounces: number
  goalassists: number
  fantasypoints: number
  timeongroundpercentage: number
}
